Algoritmo "002-nome-idade-cidade"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
// Seção de Declarações das variáveis
nome: caractere
idade: inteiro
cidade: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nome <- "Anthony"
idade <- 23
cidade <- "Boa Vista"

escreval("-----------DADOS-----------")
escreval("Nome: ", nome)
escreval("Idade: ", idade)
escreval("Cidade: ", cidade)

Fimalgoritmo