Algoritmo "004-filme"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
// Seção de Declarações das variáveis 
filme, autor: caractere
ano: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o nome do filme: ")
leia(filme)
escreva("Digite o nome do autor: ")
leia(autor)
escreva("Digite o ano do filme: ")
leia(ano)
escreval("O filme ", filme, ", estrelado por ", autor, ", foi lançado em ", ano, ".")

Fimalgoritmo