Algoritmo "006-status"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
   // Seção de Declarações das variáveis
   status: caractere

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   status <- "Rascunho"
   escreval("1 - Status: ", status)
   status <- "Em andamento"
   escreval("2 - Status: ", status)
   status <- "Concluído"
   escreval("3 - Status: ", status)

Fimalgoritmo