Algoritmo "007-nome-completo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
   // Seção de Declarações das variáveis
   nome, sobrenome: caractere

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   nome <- "Anthony"
   sobrenome <- "Kildery dos Santos Alencar"

   escreval("Nome completo: " ,nome, " " ,sobrenome, "")

Fimalgoritmo