Algoritmo "008-hora"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
   // Seção de Declarações das variáveis
   usuario: caractere
   hr, min: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite seu nome: ")
   leia(usuario)
   escreval("Digite a hora: ")
   leia(hr)
   escreval("Digite o minuto: ")
   leia(min)
   escreval("Olá " ,usuario, ", agora são " ,hr, ":" ,min, " horas.")

Fimalgoritmo