Algoritmo "009-modelo-carro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
   // Seção de Declarações das variáveis
   marca, modelo, cor: caractere

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("---------IFORME OS DADOS DO VEICULO---------")
   escreval("Digite a marca: ")
   leia(marca)
   escreval("Digite a modelo: ")
   leia(modelo)
   escreval("Digite a cor: ")
   leia(cor)

   escreval("O carro cadastrado é um " ,marca, " " ,modelo, " na cor " ,cor, ".")

Fimalgoritmo