Algoritmo "010-profissao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
   // Seção de Declarações das variáveis
   nome, profissao: caractere
   idade: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   nome <- "Anthony"
   profissao <- "Programador"
   idade <- 23
   escreval("Meu nome é " ,nome, ", tenho " ,idade, " anos e sou " ,profissao, ".")

Fimalgoritmo