Algoritmo "011-cor-animal"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
// Seção de Declarações das variáveis 
animal, cor: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite o nome do animal: ")
leia(animal)
escreval("Digite a cor do animal: ")
leia(cor)
escreval(" ")
escreval("O " ,animal, " escolhido tem a cor " ,cor, ".")

Fimalgoritmo