Algoritmo "013-disciplina"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
   // Seção de Declarações das variáveis
   disciplina, professor: caractere

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   disciplina <- "Algoritimo"
   professor <- "Rodrigo"
   escreval("A disciplina " ,disciplina, " é ministrada pelo professor " ,professor, ".")

Fimalgoritmo