Algoritmo "014-musica"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
   // Seção de Declarações das variáveis
   musica,  cantor: caractere

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   musica <- "Estilo Cachorro"
   cantor <- "Racionais"
   escreval("A música " ,musica, " é interpretada por " ,cantor, ".")

Fimalgoritmo