Algoritmo "015-empresa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
   // Seção de Declarações das variáveis
   empresa, cargo: caractere

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   empresa <- "Personal Confecções"
   cargo <- "Programador"
   escreval("Trabalho na empresa " ,empresa, " como " ,cargo, ".")

Fimalgoritmo