Algoritmo "001"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Rodrigo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Anthony Kildery
// Data atual  : 15/09/2026
Var
// Seção de Declarações das variáveis 
num1, num2, num3: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o primeiro número: ")
leia(num1)
escreva("Digite o segundo número: ")
leia(num2)
escreva("Digite o terceiro número: ")
leia(num3)

escreval("")
escreva(num1, " +" ,num2, " +" ,num3, " =", num1 + num2 + num3)

Fimalgoritmo