Algoritmo "003"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/09/2026
Var
// Seção de Declarações das variáveis
// P = 2(b + h), onde b é a base (comprimento) e h é a altura (largura).
P, b, h: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Comprimento: ")
leia(b)
escreva("Largura: ")
leia(h)

escreval("")
P <- 2 * (b + h)
escreval("Perímetro: ", P)

Fimalgoritmo