Algoritmo "005"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Rodrigo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Anthony Kildery
// Data atual  : 15/09/2026
Var
// Seção de Declarações das variáveis 
// A = p × r^2
A, r: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe o raio do círculo: ")
leia(r)

escreval("")
A <- pi * (r^2)
escreval(A:1:2, " = 3,14 × " ,r, "^2")

Fimalgoritmo