Algoritmo "006"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/09/2026
Var
// Seção de Declarações das variáveis 
idade, meses, dias: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a sua idade em anos: ")
leia(idade)

meses <- idade * 12
dias <- idade * 365

escreval("")
escreval("Meses: ", meses)
escreval("Dias: ", dias)

Fimalgoritmo