Algoritmo "002-antecessor-e-sucessor"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Anthony Kildery
// Data atual  : 17/09/2026

Var
numero: inteiro

Inicio
escreva("Digite um número inteiro: ")
leia(numero)

escreval("")
escreval("Antecessor: ", numero - 1)
escreval("Sucessor: ", numero + 1)

Fimalgoritmo
