Algoritmo "003-perimetro-de-um-quadrado"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2026
Var
lado: inteiro

Inicio
escreva("Digite a medida de um dos lados do quadrado: ")
leia(lado)

escreval("")
escreval("Perímetro: ", lado * 4)

Fimalgoritmo