Algoritmo "004-valor-total-da-compra-de-frutas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2026
Var
quilo, valor: real

Inicio
escreva("Digite os quilos da maçã: ")
leia(quilo)
escreva("Preço pago pela maçã: ")
leia(valor)

escreval("")
escreval("Total da compra: ", quilo * valor)

Fimalgoritmo