Algoritmo "005-conversao-de-minutos-em-segundos"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Rodrigo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2026
Var
min, seg: inteiro

Inicio
escreva("Informe os minutos: ")
leia(min)

escreval("")
escreval("" ,min, " min ->", min*60, " seg")

Fimalgoritmo