Algoritmo "006"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Rodrigo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2026
Var
horas: inteiro
valor: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite as horas trabalhadas em um mês: ")
leia(horas)
escreva("Valor recebido por hora: ")
leia(valor)

escreval("")
escreval("Salário total do mês: R$", horas * valor)

Fimalgoritmo