Algoritmo "008-conversor-de-metros-para-centimetros"
// Disciplina   : Linguagem e Lógica de Programação
// Professor   : Rodrigo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Anthony Kildery
// Data atual  : 17/09/2026
Var
metros: real

Inicio
escreva("Digite valor em metros: ")
leia(metros)

escreval("")
escreval(metros, " m ->" ,metros * 100, " cm")

Fimalgoritmo
