Algoritmo "008"
// Disciplina   : Linguagem e Lógica de Programação
// Professor   : Rodrigo 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2026
Var
// Seção de Declarações das variáveis
metros: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite valor em metros: ")
leia(metros)

escreval("")
escreval(metros, " m ->" ,metros * 100, " cm")

Fimalgoritmo