Algoritmo "002-par-ou-impar"
// Disciplina  : Lógica de Programaçâo
// Professor   : Rodrigo 
// Descrição   : Descreva o que o programa faz
// Autor(a)    : Anthony Kildery
// Data atual  : 06/10/2026
Var
numero: inteiro

Inicio
escreva("Informe qualquer número inteiro: ")
leia(numero)

se numero % 2 = 0 entao
   escreval("[" ,numero, " ] -> Par")
senao
   escreval("[" ,numero, " ] -> Ímpar")
fimse

Fimalgoritmo
