Algoritmo "004-validacao-de-senha-de-acesso"
// Disciplina  : Lógica de Programaçâo
// Professor   : Rodrigo 
// Descrição   : Descreva o que o programa faz
// Autor(a)    : Anthony Kildery
// Data atual  : 06/10/2026
Var
senha: inteiro

Inicio
escreva("Digite a senha: ")
leia(senha)
escreval("")

se senha = 123 entao
   escreval("ACESSO PERMITIDO")
senao
   escreval("ACESSO NEGADO")
fimse

Fimalgoritmo
